backend:
  name: git-gateway
  branch: master
media_folder: "_images/uploads"
collections:
  - name: "en" # Used in routes, e.g., /admin/collections/blog
    label: "English page" # Used in the UI
    folder: "src/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    nested: { depth: 100 }
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Translation key", name: "translationKey", widget: "string", hint: "Unique key to link to French page"}
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        hint: "Navigation setup"
        fields:
          - {label: "Key", name: "key", widget: "string"}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Locale", name: "locale", widget: "hidden", default: "en"}
          - {label: "Order", name: "order", widget: "number", value_type: "int", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: { path: { label: Parent, widget: parent, index_file: 'index' } }
  - name: "fr" # Used in routes, e.g., /admin/collections/blog
    label: "French page" # Used in the UI
    folder: "src/fr" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    nested: { depth: 100 }
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Translation key", name: "translationKey", widget: "string", hint: "Unique key to link to English page"}
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: "object"
        required: false
        hint: "Navigation setup"
        fields:
          - {label: "Key", name: "key", widget: "string"}
          - {label: "Parent", name: "parent", widget: "string", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Locale", name: "locale", widget: "hidden", default: "fr"}
          - {label: "Order", name: "order", widget: "number", value_type: "int", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: { path: { label: Parent, widget: parent, index_file: 'index' } }