backend:
  name: git-gateway
  branch: master
media_folder: "_images/uploads"
collections:
  - name: "component" # Used in routes, e.g., /admin/collections/blog
    label: "Component" # Used in the UI
    folder: "src/en/components" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    nested: { depth: 100 }
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: '"layout/base.njk"'}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    meta: { path: { label: Parent, widget: parent, index_file: 'index' } }